AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create role for Amazon Bedrock Knowledge Bases with inline policies'

Resources:
  BedrockKnowledgeBaseServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: AmazonBedrockKnowledgeBaseServiceRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: '/service-role/'
      Description: 'Service role for Amazon Bedrock Knowledge Bases'
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:GetBucketLocation'
                Resource:
                  - 'arn:aws:s3:::*'
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                Resource:
                  - 'arn:aws:s3:::*/*'
        - PolicyName: OpensearchAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'es:ESHttpGet'
                  - 'es:ESHttpPost'
                  - 'es:ESHttpPut'
                  - 'es:ESHttpDelete'
                  - 'es:DescribeDomain'
                  - 'es:ListDomainNames'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'aoss:APIAccessAll'
                  - 'aoss:DashboardsAccessAll'
                Resource: 'arn:aws:aoss:*:*:collection/*'
        - PolicyName: KmsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'kms:Decrypt'
                  - 'kms:GenerateDataKey'
                Resource: '*'
        - PolicyName: CloudWatchAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:log-group:/aws/bedrock/*'

Outputs:
  ServiceRoleARN:
    Description: 'ARN of the created service role for Bedrock Knowledge Base'
    Value: !GetAtt BedrockKnowledgeBaseServiceRole.Arn